name: CD Pipeline for dbt and Snowflake

on:
  push:
    branches:
      - main
    paths:
      - "src/dbt/**"  

jobs:
  cd-prod:
    name: CD to Prod Environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dbt and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt-snowflake

      - name: Set up dbt profile for Prod
        run: |
          mkdir -p ~/.dbt
          echo "default:
            outputs:
              prod:
                account: $SNOWFLAKE_ACCOUNT
                database: $SNOWFLAKE_DATABASE
                password: $SNOWFLAKE_PASSWORD
                role: $SNOWFLAKE_ROLE
                schema: $SNOWFLAKE_SCHEMA
                threads: 4
                type: snowflake
                user: $SNOWFLAKE_USER
                warehouse: $SNOWFLAKE_WAREHOUSE
            target: prod" > ~/.dbt/profiles.yml
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USERNAME }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE_PROD }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}

      - name: Run dbt test in Prod
        run: dbt test --target prod
        working-directory: src/dbt

      - name: Run dbt run in Prod
        run: dbt run --target prod
        working-directory: src/dbt
