name: CI Pipeline for dbt and Snowflake

on:
  pull_request:
    branches:
      - main
    paths:
      - "src/dbt/**"  
 
jobs:
  ci-dev:
    name: CI in Dev Environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dbt and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt-snowflake

      - name: Set up dbt profile for Dev
        run: |
          mkdir -p ~/.dbt
          echo "default:
            outputs:
              dev:
                account: $SNOWFLAKE_ACCOUNT
                database: $SNOWFLAKE_DATABASE
                password: $SNOWFLAKE_PASSWORD
                role: $SNOWFLAKE_ROLE
                schema: $SNOWFLAKE_SCHEMA
                threads: 4
                type: snowflake
                user: $SNOWFLAKE_USER
                warehouse: $SNOWFLAKE_WAREHOUSE
            target: dev" > ~/.dbt/profiles.yml
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USERNAME }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}

      - name: Run dbt debug
        run: dbt debug
        working-directory: src/dbt

      - name: Run dbt test
        run: dbt test
        working-directory: src/dbt

      - name: Run dbt models
        run: dbt run
        working-directory: src/dbt

  